Update extract script

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,40 +1,40 @@
 #!/bin/bash
 
 if [ -f $1 ]; then
-  case $1 in
-    *.tar.bz2|*.tbz2)
-      tar xjf $1
-      ;;
-    *.tar.gz|*.tgz)
-      tar xzf $1
-      ;;
-    *.bz2)
-      bunzip2 $1
-      ;;
-    *.rar)
-      unrar x $1
-      ;;
-    *.gz)
-      gunzip $1
-      ;;
-    *.tar)
-      tar xf $1
-      ;;
-    *.zip)
-      unzip $1
-      ;;
-    *.Z)
-      uncompress $1
-      ;;
-    *.7z|*.xz)
-      7z x $1
-      ;;
-    *)
-      echo "'$1' cannot be extracted via extract." 1>&2
-      exit 127
-      ;;
-  esac
+	case $1 in
+	*.tar.bz2|*.tbz2)
+		tar xjf $1
+	;;
+	*.tar.gz|*.tgz)
+		tar xzf $1
+	;;
+	*.bz2)
+		bunzip2 $1
+	;;
+	*.rar)
+		unrar x $1
+	;;
+	*.gz)
+		gunzip $1
+	;;
+	*.tar)
+		tar xf $1
+	;;
+	*.zip)
+		unzip $1
+	;;
+	*.Z)
+		uncompress $1
+	;;
+	*.7z|*.xz)
+		7z x $1
+	;;
+	*)
+		echo "'$1' cannot be extracted via extract." 1>&2
+		exit 2
+	;;
+	esac
 else
-  echo "'$1' is not a valid file" 1>&2
-  exit 128
+	echo "'$1' is not a valid file" 1>&2
+	exit 1
 fi
