Update Vim modules

diff --git a/bin/git-empty b/bin/git-empty
--- a/bin/git-empty
+++ b/bin/git-empty
@@ -1,17 +1,30 @@
 #!/bin/bash
+set -eu -o pipefail
 
 function usage() {
-	echo "usage: git empty [-h] directory" 1>&2
+	echo "Usage: git empty [-h] [-d] [directory]" 1>&2
+	echo "	-h Show help" 1>&2
+	echo "	-d Decorate .gitignore with common OS files" 1>&2
+	echo "If no directory is given then current directory is used as working directory." 1>&2
 }
 
-if [ "$1" == "-h" ]; then
-	usage
-	exit 1
-fi
-if [ -z "$1" ]; then
-	dir=.
+while getopts "hd" arg; do
+	case $arg in
+	d) # Decorate .gitignore with common OS files
+		deco_arg=1
+		shift
+	;;
+	h|*) # Show help
+		usage
+		exit 1
+	;;
+	esac
+done
+
+if [ -n "${1-}" ]; then
+	dir=${1}
 else
-	dir=$1
+	dir=.
 fi
 if [ ! -d "$dir" ]; then
 	mkdir -p "$dir"
@@ -19,7 +32,7 @@ fi
 
 cd "$dir" || exit 3
 if [ -d .git ]; then
-	echo "git-empty: existing .git directory found. aborting." 1>&2
+	echo "git empty: existing .git directory found. aborting." 1>&2
 	exit 2
 fi
 git init .
@@ -28,19 +41,36 @@ if [ -e .gitignore ]; then
 	mv .gitignore "$tmpignore"
 fi
 
-email="kare.nuorteva@me.com"
-case $(hostname) in
-	"Kare-MacBook-Pro.local")
-		email="kare.nuorteva@streamr.com"
-	;;
-esac
-git config user.email "$email"
+git config user.email kare.nuorteva@me.com
 git config user.name "Kare Nuorteva"
-git config color.ui false
+git config color.ui true
 
 touch .gitignore
 git add .gitignore
-git commit -m "Add empty .gitignore"
-if [ -e "$tmpignore" ]; then
+git commit -m "chore: Add empty .gitignore"
+if [ -n "${tmpignore-}" ] && [ -e "$tmpignore" ]; then
 	mv "$tmpignore" .gitignore
 fi
+
+if [[ -n ${deco_arg-} ]]; then
+	if [[ $(git diff-index --quiet HEAD .gitignore) ]]; then
+		git stash
+		deco_stash=1
+	fi
+	cat << __DECORATION__ >> .gitignore
+.DS_Store
+/.idea
+/.vscode
+*.diff
+*.patch
+*.tar.gz
+*.tgz
+*.zip
+__DECORATION__
+fi
+git add .gitignore
+git commit -m "chore: Add common files to .gitignore"
+if [ -n "${deco_stash-}" ] && [ -e "$deco_stash" ]; then
+	git stash pop
+fi
+
diff --git a/bin/go-update-tools b/bin/go-update-tools
--- a/bin/go-update-tools
+++ b/bin/go-update-tools
@@ -5,12 +5,11 @@ if [ "$GOPATH" != "$HOME" ]; then
 	exit 1
 fi
 
-#rsc.io/github/...
+#github.com/uudashr/gopkgs/cmd/gopkgs
 read -r -d '' packages << __HERE__
 9fans.net/go/acme/Watch
 9fans.net/go/acme/acmego
 9fans.net/go/acme/editinacme
-github.com/FiloSottile/mkcert
 github.com/acroca/go-symbols
 github.com/alexkohler/prealloc
 github.com/campoy/jsonenums
@@ -20,9 +19,11 @@ github.com/davidrjenni/reftools/cmd/fillstruct
 github.com/farhaven/acme-complete-bind
 github.com/fatih/gomodifytags
 github.com/fhs/acme-lsp/cmd/L
-github.com/fzipp/gocyclo
+github.com/fhs/acme-lsp/cmd/acme-lsp
+github.com/fzipp/gocyclo/cmd/gocyclo
 github.com/go-delve/delve/cmd/dlv
 github.com/godoctor/godoctor
+github.com/golang/mock/mockgen
 github.com/golang/protobuf/protoc-gen-go
 github.com/gordonklaus/ineffassign
 github.com/goreleaser/goreleaser
@@ -35,9 +36,11 @@ github.com/klauspost/asmfmt/cmd/asmfmt
 github.com/mdempsky/maligned
 github.com/mdempsky/unconvert
 github.com/monochromegane/the_platinum_searcher/...
+github.com/nishanths/exhaustive/cmd/exhaustive
 github.com/nsf/gocode
 github.com/quasilyte/go-parsefix/cmd/parsefix
 github.com/rakyll/hey
+github.com/ramya-rao-a/go-outline
 github.com/ramya-rao-a/go-outline
 github.com/rjeczalik/bin/cmd/gobin
 github.com/rjkroege/edwood
@@ -49,7 +52,8 @@ github.com/shurcooL/markdownfmt
 github.com/tommy-muehle/go-mnd/cmd/mnd
 github.com/tsenart/deadcode
 github.com/tsenart/vegeta
-github.com/uudashr/gopkgs/cmd/gopkgs
+github.com/vektra/mockery/v2
+github.com/yagipy/maintidx/cmd/maintidx
 github.com/zmb3/gogetdoc
 gitlab.com/opennota/check/cmd/aligncheck
 gitlab.com/opennota/check/cmd/structcheck
@@ -66,6 +70,7 @@ golang.org/x/tools/cmd/godoc
 golang.org/x/tools/cmd/goimports
 golang.org/x/tools/cmd/gomvpkg
 golang.org/x/tools/cmd/gotype
+golang.org/x/tools/cmd/goyacc
 golang.org/x/tools/cmd/guru
 golang.org/x/tools/cmd/present
 golang.org/x/tools/cmd/stringer
@@ -83,9 +88,9 @@ sourcegraph.com/sqs/goreturns
 __HERE__
 
 for pkg in $packages; do
-	echo "gp-update-tools: installing $pkg@latest"
-	if ! go get -u "$pkg@latest"; then
-		echo "go-update-tools: 'go get' error for package '$pkg'" 1>&2
+	echo "go-update-tools: installing $pkg@latest"
+	if ! go install "$pkg@latest"; then
+		echo "go-update-tools: 'go install' error for package '$pkg'" 1>&2
 	fi
 done
 
