go-update-tools: Split script for 'go get' and 'go install'

diff --git a/bin/go-update-tools b/bin/go-update-tools
--- a/bin/go-update-tools
+++ b/bin/go-update-tools
@@ -55,11 +55,6 @@ honnef.co/go/tools/cmd/gosimple
 honnef.co/go/tools/cmd/megacheck
 honnef.co/go/tools/cmd/staticcheck
 honnef.co/go/tools/cmd/unused
-kkn.fi/cmd/gends
-kkn.fi/cmd/gist
-kkn.fi/cmd/itob
-kkn.fi/cmd/tcpproxy
-kkn.fi/cmd/vanity
 mvdan.cc/interfacer
 rsc.io/goversion
 __HERE__
@@ -68,6 +63,21 @@ for pkg in $packages; do
 	echo "go get -u $pkg"
 	go get -u $pkg
 	if [ $? -ne 0 ]; then
-		echo "go-update-tools: failed to load Go package '$pkg'" 1>&2
+		echo "go-update-tools: 'go get' error for package '$pkg'" 1>&2
+	fi
+done
+
+read -r -d '' packages << __HERE__
+kkn.fi/cmd/gends
+kkn.fi/cmd/gist
+kkn.fi/cmd/itob
+kkn.fi/cmd/tcpproxy
+__HERE__
+
+for pkg in $packages; do
+	echo "go install $pkg"
+	go install $pkg
+	if [ $? -ne 0 ]; then
+		echo "go-update-tools: 'go install' error for package '$pkg'" 1>&2
 	fi
 done
